import { IGiftCards } from "@/types/IGiftCards";

const giftCardsData: IGiftCards[] = [
  {
    id: 1,
    title: "Aspirador de pó vertical",
    price: 150.99,
    image: "/gifts/aspirador-de-po-vertical-2.jpg",
    isDisabled: false,
  },
  {
    id: 2,
    title: "Ferro de passar roupas",
    price: 120.0,
    image: "/gifts/ferro-de-passar-roupas.jpg",
    isDisabled: false,
  },
  {
    id: 3,
    title: "Batedeira",
    price: 159.0,
    image: "/gifts/batedeira.jpg",
    isDisabled: false,
  },
  {
    id: 4,
    title: "Mixer",
    price: 150.0,
    image: "/gifts/mixer.jpg",
    isDisabled: false,
  },
  {
    id: 5,
    title: "Sanduicheira elétrica",
    price: 100.99,
    image: "/gifts/sanduicheira-eletrica.webp",
    isDisabled: false,
  },
  {
    id: 6,
    title: "Panela de arroz elétrica",
    price: 170.99,
    image: "/gifts/panela-de-arroz-eletrica.webp",
    isDisabled: false,
  },
  {
    id: 7,
    title: "Multi processador",
    price: 200.0,
    image: "/gifts/multi-processador.webp",
    isDisabled: false,
  },
  {
    id: 8,
    title: "Faqueiro",
    price: 250.99,
    image: "/gifts/faqueiro.webp",
    isDisabled: false,
  },
  {
    id: 9,
    title: "Aparelho de Jantar",
    price: 180.0,
    image: "/gifts/aparelho-de-jantar.webp",
    isDisabled: false,
  },
  {
    id: 10,
    title: "Jogo de taças de vinho",
    price: 100.50,
    image: "/gifts/jogo-de-tacas-de-vinho.webp",
    isDisabled: false,
  },
  {
    id: 11,
    title: "Conjunto para sobremesa",
    price: 99.99,
    image: "/gifts/conjunto-para-sobremesa.webp",
    isDisabled: false,
  },
  {
    id: 12,
    title: "Travessas de vidro ou porcelana",
    price: 120.0,
    image: "/gifts/travessas-de-vidro-ou-porcelana.webp",
    isDisabled: false,
  },
  {
    id: 13,
    title: "Jogo de toalhas de banho",
    price: 100.0,
    image: "/gifts/jogo-de-toalhas-de-banho.webp",
    isDisabled: false,
  },
  {
    id: 14,
    title: "Jogo de cama (queen)",
    price: 200.0,
    image: "/gifts/jogo-de-cama-queen.jpg",
    isDisabled: false,
  },
  {
    id: 15,
    title: "Grill",
    price: 135.99,
    image: "/gifts/grill.webp",
    isDisabled: false,
  },
  {
    id: 16,
    title: "Jogo de copos",
    price: 89.99,
    image: "/gifts/jogo-de-copos.jpg",
    isDisabled: false,
  },
  {
    id: 17,
    title: "Chaleira elétrica",
    price: 99.0,
    image: "/gifts/chaleira-eletrica.webp",
    isDisabled: false,
  },
  {
    id: 18,
    title: "Chaleira ",
    price: 79.99,
    image: "/gifts/chaleira.webp",
    isDisabled: false,
  },
  {
    id: 19,
    title: "Garrafa térmica",
    price: 89.0,
    image: "/gifts/garrafa-termica.webp",
    isDisabled: false,
  },
  {
    id: 20,
    title: "Jogo de Panelas",
    price: 300.0,
    image: "/gifts/jogo-de-panelas.webp",
    isDisabled: false,
  },
  {
    id: 21,
    title: "Saladeira",
    price: 90.0,
    image: "/gifts/saladeira.webp",
    isDisabled: false,
  },
  {
    id: 22,
    title: "Jarra de vidro para suco",
    price: 89.0,
    image: "/gifts/jarra-de-vidro-para-suco.webp",
    isDisabled: false,
  },
  {
    id: 23,
    title: "Jogo de taça de champagne",
    price: 100.5,
    image: "/gifts/jogo-de-taca-de-champagne.webp",
    isDisabled: false,
  },
  {
    id: 24,
    title: "Edredom queen",
    price: 300.5,
    image: "/gifts/edredom-queen.webp",
    isDisabled: false,
  },
  {
    id: 25,
    title: "Tábuas para corte",
    price: 150.0,
    image: "/gifts/tabuas-para-corte.webp",
    isDisabled: false,
  },
];

export default giftCardsData;
