import { IGiftCards } from "@/types/IGiftCards";

const giftCardsData: IGiftCards[] = [
  {
    id: 1,
    title: "Aspirador de pó vertical",
    price: 49.99,
    image: "/gifts/aspirador-de-po-vertical-2.jpg",
    isDisabled: false,
  },
  {
    id: 2,
    title: "Ferro de passar roupas",
    price: 19.0,
    image: "/gifts/ferro-de-passar-roupas.jpg",
    isDisabled: false,
  },
  {
    id: 3,
    title: "Batedeira",
    price: 59.0,
    image: "/gifts/batedeira.jpg",
    isDisabled: false,
  },
  {
    id: 4,
    title: "Mixer",
    price: 19.99,
    image: "/gifts/mixer.jpg",
    isDisabled: false,
  },
  {
    id: 5,
    title: "Sanduicheira elétrica",
    price: 39.99,
    image: "/gifts/sanduicheira-eletrica.png",
    isDisabled: false,
  },
  {
    id: 6,
    title: "Panela de arroz elétrica",
    price: 29.99,
    image: "/gifts/panela-de-arroz-eletrica.jpg",
    isDisabled: false,
  },
  {
    id: 7,
    title: "Multi processador",
    price: 39.99,
    image: "/gifts/multi-processador.jpg",
    isDisabled: false,
  },
  {
    id: 8,
    title: "Faqueiro",
    price: 29.99,
    image: "/gifts/faqueiro.jpg",
    isDisabled: false,
  },
  {
    id: 9,
    title: "Aparelho de Jantar",
    price: 45.99,
    image: "/gifts/aparelho-de-jantar.jpg",
    isDisabled: false,
  },
  {
    id: 10,
    title: "Jogo de taças de vinho",
    price: 17.99,
    image: "/gifts/jogo-de-tacas-de-vinho.jpg",
    isDisabled: false,
  },
  {
    id: 11,
    title: "Conjunto para sobremesa",
    price: 14.99,
    image: "/gifts/conjunto-para-sobremesa.jpg",
    isDisabled: false,
  },
  {
    id: 12,
    title: "Travessas de vidro ou porcelana",
    price: 12.99,
    image: "/gifts/travessas-de-vidro-ou-porcelana.jpg",
    isDisabled: false,
  },
  {
    id: 13,
    title: "Jogo de toalhas de banho",
    price: 37.99,
    image: "/gifts/jogo-de-toalhas-de-banho.jpg",
    isDisabled: false,
  },
  {
    id: 14,
    title: "Jogo de cama (queen)",
    price: 75.99,
    image: "/gifts/jogo-de-cama-queen.jpg",
    isDisabled: false,
  },
  {
    id: 15,
    title: "Grill",
    price: 24.99,
    image: "/gifts/grill.jpg",
    isDisabled: false,
  },
  {
    id: 16,
    title: "Jogo de copos",
    price: 11.99,
    image: "/gifts/jogo-de-copos.jpg",
    isDisabled: false,
  },
  {
    id: 17,
    title: "Chaleira elétrica",
    price: 16.99,
    image: "/gifts/chaleira-eletrica.jpg",
    isDisabled: false,
  },
  {
    id: 18,
    title: "Chaleira ",
    price: 9.99,
    image: "/gifts/chaleira.jpg",
    isDisabled: false,
  },
  {
    id: 19,
    title: "Garrafa térmica",
    price: 19.99,
    image: "/gifts/garrafa-termica.jpg",
    isDisabled: false,
  },
  {
    id: 20,
    title: "Jogo de Panelas",
    price: 29.99,
    image: "/gifts/jogo-de-panelas.jpg",
    isDisabled: false,
  },
  {
    id: 21,
    title: "Saladeira",
    price: 10.99,
    image: "/gifts/saladeira.jpg",
    isDisabled: false,
  },
  {
    id: 22,
    title: "Jarra de vidro para suco",
    price: 15.0,
    image: "/gifts/jarra-de-vidro-para-suco.jpg",
    isDisabled: false,
  },
  {
    id: 23,
    title: "Jogo de taça de champagne",
    price: 19.5,
    image: "/gifts/jogo-de-taca-de-champagne.jpg",
    isDisabled: false,
  },
  {
    id: 24,
    title: "Edredom queen",
    price: 57.99,
    image: "/gifts/edredom-queen.jpg",
    isDisabled: false,
  },
  {
    id: 25,
    title: "Tábuas para corte",
    price: 19.99,
    image: "/gifts/tabuas-para-corte.jpg",
    isDisabled: false,
  },
];

export default giftCardsData;
